name: thirdproject
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.8.0
  flutter_svg: ^1.0.0
  http: ^0.13.5
  table_calendar: ^3.0.9
  intl: ^0.18.1
  provider: ^6.1.2
  logger: ^2.5.0
  url_launcher: ^6.3.1
  multi_dropdown: ^3.0.1
  multiselect_dropdown_flutter: ^0.0.7
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.svg
